# Generated by Django 3.2.10 on 2023-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceData',
            fields=[
                ('sentenceNum', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('hint', models.CharField(max_length=100)),
                ('blankWord', models.CharField(max_length=50)),
                ('blankPos', models.IntegerField()),
                ('ansKor', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
