# Generated by Django 4.2 on 2023-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20230427_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='유저ID')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
            ],
            options={
                'db_table': 'test_user',
            },
        ),
    ]
