# Generated by Django 4.2.1 on 2023-05-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_idx',
            field=models.IntegerField(default=0, verbose_name='유저학습문장번호'),
        ),
    ]
