# Generated by Django 4.2 on 2023-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_user_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.CharField(default='', max_length=1000, verbose_name='북마크'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_idx',
            field=models.IntegerField(default=1, verbose_name='유저학습문장번호'),
        ),
    ]
